### ISSUE TITLE
NEAT utilities are not working

### ISSUE THREAD

**Issue by nilchia** [ncsa/NEAT#112]
NEAT version 4.2.1

**Bug in gen-mut-model**

gen-mut-model gives the following error:
`TypeError: compute_mut_runner() missing 1 required positional argument: 'overwrite_output'`

Maybe this is related to [this update](https://github.com/ncsa/NEAT/commit/98fb3baa964dbc4d104f913efd4f8641a82b6634#diff-e235c411d20b004995742d4be80581430250cd3d1c632f197f4fe23f71aac42f) where the `arguments.save_trinuc,` was deleted from "gen_mut_model.py" but it is still remaining in the [gen_mut_model/runner.py](https://github.com/ncsa/NEAT/blob/f33455695d57146852017a7eef7cded1ea6cc58e/neat/gen_mut_model/runner.py#L37C10-L37C24)

**To Reproduce**
run the following simple command:
```
neat gen-mut-model H1N1.fa H1N1.vcf -o mutmodel
```
-----
**Bug in model-fraglen**

model-fraglen gives the following error:
`TypeError: FragmentLengthModel.__init__() takes from 3 to 4 positional arguments but 5 were given`

**To Reproduce**
run the following simple command:
```
neat model-fraglen -i test.bam -o fraglen
```
-----

**Comment by joshfactorial** [comment]
I'll look at this, thanks!

**Comment by joshfactorial** [comment]
Okay, the first issue looked to me like I made a mistake while merging or made a mistake while trying to revise one of the models. Either way, i added the save_trinuc back in, since it shouldn't have been deleted, I don't think. Both seem to be working now in develop. I couldn't replicate the fragelen error, so I suspect a code change I made for another bug resolved that one. I'll issue a new version soon to cover these issues.

**Comment by nilchia** [comment]
That is great. Thanks for the rapid fix, Joshua.

**Comment by bgruening** [comment]
Cool, thanks @joshfactorial for cutting a release soon!

**Comment by nilchia** [comment]
Hello, @joshfactorial.
Thanks for fixing the issue.
I am facing a new problem now :)
when using `gen-mut-model` with the `--outcounts` argument and a trinucleotide counts file I get this error:
```
2024-07-07 20:42:46,413:INFO:neat.gen_mut_model.utils:Loading file: neat_gen-mut-model.trinuc.pickle.gz.
2024-07-07 20:42:46,413:ERROR:neat:gen-mut-model failed, see the traceback below
Traceback (most recent call last):
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/site-packages/neat/cli/cli.py", line 131, in main
    cmd(args)
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/site-packages/neat/cli/commands/gen_mut_model.py", line 91, in execute
    compute_mut_runner(arguments.reference, arguments.mutations, arguments.bed, arguments.outcounts,
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/site-packages/neat/gen_mut_model/runner.py", line 480, in compute_mut_runner
    runner(reference_index, vcf_to_process, vcf_columns, outcounts, show_trinuc, save_trinuc,
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/site-packages/neat/gen_mut_model/runner.py", line 96, in runner
    trinuc_ref_count, bed_track_length = count_trinucleotides(reference_index,
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/site-packages/neat/gen_mut_model/utils.py", line 229, in count_trinucleotides
    trinuc_ref_count = json.load(counts)
                       ^^^^^^^^^^^^^^^^^
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
ERROR: gen-mut-model failed, showing the last error
Traceback (most recent call last):
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/site-packages/neat/cli/cli.py", line 131, in main
    cmd(args)
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/site-packages/neat/cli/commands/gen_mut_model.py", line 91, in execute
    compute_mut_runner(arguments.reference, arguments.mutations, arguments.bed, arguments.outcounts,
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/site-packages/neat/gen_mut_model/runner.py", line 480, in compute_mut_runner
    runner(reference_index, vcf_to_process, vcf_columns, outcounts, show_trinuc, save_trinuc,
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/site-packages/neat/gen_mut_model/runner.py", line 96, in runner
    trinuc_ref_count, bed_track_length = count_trinucleotides(reference_index,
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/site-packages/neat/gen_mut_model/utils.py", line 229, in count_trinucleotides
    trinuc_ref_count = json.load(counts)
                       ^^^^^^^^^^^^^^^^^
  File "/home/nilchia/miniconda3/envs/neat/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
here is the code I used:
`neat --log-name neat_gen-mut-model gen-mut-model H1N1.fa H1N1.vcf -o neat_gen-mut-model --save-trinuc`
and 
`neat --log-name neat_gen-mut-model2 gen-mut-model H1N1.fa H1N1.vcf -o neat_gen-mut-model2 --outcounts neat_gen-mut-model.trinuc.pickle.gz`

Would you please help me with that?
Thanks
