### ISSUE TITLE
Error when sampling reads

### ISSUE THREAD

**Issue by mattbird567** [ncsa/NEAT#70]
**Describe the bug**
Hello, 

I am trying to use NEAT to geerate some synthetic TB reads using a VCF file to introduce known mutations that are associated with antibiotic resistance. When i am running my code (seen below) i am getting an error that i think is related to BioPython. I'm not sure if its related to the releas of biopython i am using which is v1.80 (installed using conda). Or if its related to the way my reference and vcf are formatted so for clarity i have attached them below as well (as .txt as github doesn't support .vcf or .fasta). Any help would be greatly appreciated. 

### Below is the error that i am experencing

```
(base) [matthew.bird syn-data]$ python3 NEAT/gen_reads.py -r reference/TB_ref.fasta -R 300 -v simulated_reads_c100.vcf -c 100 --pe 300 1 -o simulated_reads_c100

Using default sequencing error model.
Warning: Read length of error model (147) does not match -R value (300), rescaling model...
Using default gc-bias model.
Using artificial fragment length distribution. mean=300 std=1
Index not found, creating one... 
0.022 (sec)
--------------------------------
reading input VCF...

Warning: Found variants without a GT field, assuming heterozygous...
found 16 valid variants in input vcf.
 * 0 variants skipped: (qual filtered / ref genotypes / invalid syntax)
 * 0 variants skipped due to multiple variants found per position
--------------------------------
reading ChrI... 
2.210 (sec)
found 16 valid variants for ChrI in input VCF...
--------------------------------
sampling reads...
[Traceback (most recent call last):
  File "NEAT/gen_reads.py", line 896, in <module>
    main()
  File "NEAT/gen_reads.py", line 618, in main
    all_inserted_variants = sequences.random_mutations()
  File "/hpscol02/tenant2/hpc_storage/home/matthew.bird/syn-data/NEAT/source/SequenceContainer.py", line 602, in random_mutations
    temp = MutableSeq(self.sequences[i])
  File "/home/matthew.bird/anaconda3/lib/python3.8/site-packages/Bio/Seq.py", line 1662, in __init__
    raise TypeError(
TypeError: The sequence data given to a MutableSeq object should be a string or an array (not a Seq object etc)
```

[simulated_reads_c100.txt](https://github.com/ncsa/NEAT/files/10755902/simulated_reads_c100.txt)
[TB_ref.txt](https://github.com/ncsa/NEAT/files/10755905/TB_ref.txt)

**Comment by joshfactorial** [comment]
I tried this both with the version of Biopython I had initially installed (1.79) and the version you mentioned (1.80). I did not see that error. Installing 1.78 is what finally replicated this error. It should work with any Biopython > 1.78, after which they completely changed how they did MutableSeqs. I would check your environment to make sure you have 1.80 installed (1.78 may have been installed with pip).
