### ISSUE TITLE
Can't run read-simulator. Probably dependency problem

### ISSUE THREAD

**Issue by shafayetrahat** [ncsa/NEAT#87]
**Description**
When running 
`neat run-simulator -c config.yaml -o simulated data` gives me error
`Traceback (most recent call last):
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/cli/cli.py", line 133, in main
    cmd(args)
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/cli/commands/read_simulator.py", line 47, in execute
    read_simulator_runner(arguments.config, arguments.output)
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/read_simulator/runner.py", line 268, in read_simulator_runner
    output_file_writer = OutputFileWriter(options=options,
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/read_simulator/utils/output_file_writer.py", line 138, in __init__
    with open_output(self.vcf_fn, mode=mode) as vcf_file:
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/common/io.py", line 103, in open_output
    handle = open_(output_path, mode=mode)
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/Bio/bgzf.py", line 277, in open
    raise ValueError("Bad mode %r" % mode)
ValueError: Bad mode 'xt'
ERROR: read-simulator failed, showing the last error
Traceback (most recent call last):
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/cli/cli.py", line 133, in main
    cmd(args)
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/cli/commands/read_simulator.py", line 47, in execute
    read_simulator_runner(arguments.config, arguments.output)
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/read_simulator/runner.py", line 268, in read_simulator_runner
    output_file_writer = OutputFileWriter(options=options,
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/read_simulator/utils/output_file_writer.py", line 138, in __init__
    with open_output(self.vcf_fn, mode=mode) as vcf_file:
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/common/io.py", line 103, in open_output
    handle = open_(output_path, mode=mode)
  File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/Bio/bgzf.py", line 277, in open
    raise ValueError("Bad mode %r" % mode)
ValueError: Bad mode 'xt'`

**To Reproduce**
Fresh installation gives me the error
Installation steps
> conda env create -f environment.yml -n neat
> conda activate neat
> poetry build
> pip install dist/neat*whl
And follow 
[contents of neat_config.yml]
reference: H1N1.fasta
read_len: 126
produce_bam: True
produce_vcf: True
paired_ended: True
fragment_mean: 300
fragment_st_dev: 30
input_variants: H1N1.vcf
mutation_rate: 0

neat read-simulator                 \
        -c neat_config.yml          \
        -o /home/me/simulated_reads

**Additional context**
**Suggest me how to solve this problem?**

**Comment by joshfactorial** [comment]
Apologies, we recently discovered this bug as well and are working through it.
________________________________
From: Shafayet Islam ***@***.***>
Sent: Monday, October 23, 2023 4:22 PM
To: ncsa/NEAT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ncsa/NEAT] Can't run read-simulator. Probably dependency problem (Issue #87)


Describe the bug
When running neat run-simulator -c config.yaml -o simulated data it gives me error
Traceback (most recent call last):
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/cli/cli.py", line 133, in main
cmd(args)
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/cli/commands/read_simulator.py", line 47, in execute
read_simulator_runner(arguments.config, arguments.output)
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/read_simulator/runner.py", line 268, in read_simulator_runner
output_file_writer = OutputFileWriter(options=options,
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/read_simulator/utils/output_file_writer.py", line 138, in init
with open_output(self.vcf_fn, mode=mode) as vcf_file:
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/contextlib.py", line 135, in enter
return next(self.gen)
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/common/io.py", line 103, in open_output
handle = open_(output_path, mode=mode)
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/Bio/bgzf.py", line 277, in open
raise ValueError("Bad mode %r" % mode)
ValueError: Bad mode 'xt'
ERROR: read-simulator failed, showing the last error
Traceback (most recent call last):
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/cli/cli.py", line 133, in main
cmd(args)
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/cli/commands/read_simulator.py", line 47, in execute
read_simulator_runner(arguments.config, arguments.output)
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/read_simulator/runner.py", line 268, in read_simulator_runner
output_file_writer = OutputFileWriter(options=options,
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/read_simulator/utils/output_file_writer.py", line 138, in init
with open_output(self.vcf_fn, mode=mode) as vcf_file:
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/contextlib.py", line 135, in enter
return next(self.gen)
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/neat/common/io.py", line 103, in open_output
handle = open_(output_path, mode=mode)
File "/home/shafayetrahat/miniconda3/envs/neat/lib/python3.10/site-packages/Bio/bgzf.py", line 277, in open
raise ValueError("Bad mode %r" % mode)
ValueError: Bad mode 'xt'

To Reproduce
Fresh installation gives me the error
Installation steps

conda env create -f environment.yml -n neat
conda activate neat
poetry build
pip install dist/neat*whl
And follow
[contents of neat_config.yml]
reference: hg19.fa
read_len: 126
produce_bam: True
produce_vcf: True
paired_ended: True
fragment_mean: 300
fragment_st_dev: 30
input_variants: NA12878.vcf
mutation_rate: 0

neat read-simulator
-c neat_config.yml
-o /home/me/simulated_reads

Expected behavior
A clear and concise description of what you expected to happen.

Additional context
Suggest me how to solve this problem?

**Comment by shafayetrahat** [comment]
Thanks  
![image](https://github.com/ncsa/NEAT/assets/12217769/f3059666-459c-4b7b-927d-8176ff6bb7c2)
Just a small confusion: if I want to simulate with specified snps **without any introduced sequence error in gold standard vcf file,**  is the above mentioned command enough or do I need to use other option also. I am asking because of this --- **Unless specified, the simulator will also insert some "sequencing error" -- random variants in some reads that represents false positive results from sequencing.**

**Comment by joshfactorial** [comment]
Yes, -M 0 should set the random mutation rate to 0.
________________________________

**Comment by joshfactorial** [comment]
I take it back, this is the parameter of interest for sequencing errors:

parser.add_argument('-E', type=float, required=False, metavar='Error rate', default=-1,
                        help="Rescale avg sequencing error rate to this, must be between 0.0 and 0.3")

so it would be something like -E 0.0
________________________________

**Comment by joshfactorial** [comment]
I pushed a change to the Develop branch that should resolve this. Please let me know if your run works on the Dev branch!

**Comment by shafayetrahat** [comment]
Now, I am facing another error. I'm not very sure if it's my configuration file problem or something else. 
![image](https://github.com/ncsa/NEAT/assets/12217769/5b5bf088-a757-4726-a336-2687e4a4bf8a)

My config.yml file

[neat_config]
reference: H1N1.fa
read_len: 126
produce_bam: True
produce_vcf: True
paired_ended: True
fragment_mean: 300
fragment_st_dev: 30
input_variants: H1N1.vcf
mutation_rate: 0

neat read-simulator                 \
        -c neat_config.yml          \
        -o /home/me/simulated_reads

**Comment by shafayetrahat** [comment]
Sorry, it was from my config.yml file. After using 
reference: H1N1.fa
read_len: 126
produce_bam: True
produce_vcf: True
paired_ended: True
fragment_mean: 300
fragment_st_dev: 30
input_variants: H1N1.vcf
mutation_rate: 0
Config I am getting  
![image](https://github.com/ncsa/NEAT/assets/12217769/066fbc38-2d62-46e2-9fe7-e1ed27f86c71)

**Comment by shafayetrahat** [comment]
Can you please confirm if there's something wrong with your codebase or from my end?

**Comment by joshfactorial** [comment]
Yes, this is a bug we're working through. Did you try checking out the Develop branch? Did it still give you that error? Apologies. If you would like, the previous release (3.4) should be stable. It works a bit different, more command-line flags oriented, but it should produce good results.

**Comment by shafayetrahat** [comment]
I think it still needs some change cause I am still facing some errors.
![image](https://github.com/ncsa/NEAT/assets/12217769/c2969b2e-1791-4f1e-b77a-49bc61c0282a)

**Comment by joshfactorial** [comment]
okay, I think I resolved that.

**Comment by sfragkoul** [comment]
Hey there. I was wonderig if the bug has been resolved.

![image](https://github.com/ncsa/NEAT/assets/79847870/87ed0cca-b883-4d24-8bad-b3d21666f18c)

my config file has these args:

```reference: TP53.fasta
read_len: 126
produce_bam: True
produce_vcf: True
paired_ended: True
fragment_mean: 300
fragment_st_dev: 30 
```

The command I am running is tehe following:
`neat read-simulator -c neat_config2.yml -o simulated_data`

I am using **NEAT develop** branch.

Thank a lot for all your efforts so far!

Stella

**Comment by joshfactorial** [comment]
Yes, I believe it is. Please try the develop branch and let me know if the error persists!

**Comment by joshfactorial** [comment]
Did you try again in the last day or so? I pushed a change to develop on 11/28 that I think addresses this.
